M48
; DRILL file {KiCad 9.0.2} date 2025-07-17T17:29:35-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-17T17:29:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X126.22Y-115.5
X132.0Y-115.5
T2
X121.3Y-94.1
X121.3Y-119.5
X196.3Y-94.1
X196.3Y-119.5
M30
